# Site settings
title: MonadWizard
description: "A minimal blog template, build with Jekyll."
url: "https://monadwizard.live"
author:
  name: "Rakib Hasan"
  email: "monad.wizard.r@gmail.com"
  url: "https://monadwizard.live/blog"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"


# Options
custom_header: false
custom_nav_footer: false
reverse: false
